global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "log-processor"
    static_configs:
      - targets: ["log-processor:8080"]
    scrape_interval: 1s
    metrics_path: /metrics
